@protocol= http
@domainname= localhost
@port= {{$dotenv PORT}}
@path=v1
@baseUrl = {{protocol}}://{{domainname}}:{{port}}/{{path}}

### Model
GET {{baseUrl}}

### 

### Local - route pour récupérer les musiques
GET {{baseUrl}}/
